Yokozuna59/auto-registrar

.markdownlint.json
README.md

Update readme accord to lint

---

src/main.py

Fix windows coloring in cmd

---

src/c4c.py
src/cli.py
src/config.py
src/main.py
src/registrar_courses.py
src/registrar_requests.py
src/user_search.py

update script to black style

---

install.ps1
install.sh

udpate install files with python installation and use install webdriver repo

---

install.sh

Edit python_local_version if command `python` does not exists error in `install.sh`.

edit python_local_version error

---

auto_registrar/main.py
auto_registrar/universities/kfupm.py

- Add two classes `KFUPM_banner9` and `KFUPM_registrar`.
- Re-structured `kfupm.py` with better organization.
- Add source variable for better sorting.
- Enhance line length algorithm.
And much more...

Restructure kfupm py with new classes

---

install.sh

reverse python2 and python3 if statement

---

requirements.txt

udpate requirements.txt with

---

auto_registrar/universities/kfupm/kfupm.py

run alarm on threads

---

auto_registrar/universities/kfupm/kfupm.py

copy search_filter by value instead of reference

---

auto_registrar/tui/questions.py
auto_registrar/universities/kfupm/registrar.py

update project when course offering api is under maintenance

---

auto_registrar/universities/kfupm/banner9.py

add .json() method to get request as json type

---

auto_registrar/tui/bar.py

fix progress bar percentage output

---

auto_registrar/universities/kfupm/banner9.py

create get_user_schedule function

---

auto_registrar/tui/questions.py

merge stashed

---

install.ps1

update required python version into 3.10 and fix boolean expression

---

auto_registrar/universities/kfupm/kfupm.py
requirements.txt

remove vlc and re-add playsounds

---

.yamllint.yaml

chore: apply configuration for yaml files

---

.pre-commit-config.yaml

chore: create pre-commit hooks

---

scripts/install.sh

Fix(typo): isntall ~> install
